include tools/dev/makefiles/docker.mk
include tools/dev/makefiles/git.mk
include tools/dev/makefiles/go-sqlc.mk
include tools/dev/makefiles/docker.mk
include tools/dev/makefiles/go.mk
include tools/dev/makefiles/gobin.mk
include tools/dev/makefiles/kind.mk
include tools/dev/makefiles/kubectl.mk
include tools/dev/makefiles/openapi.mk
include tools/dev/makefiles/skaffold.mk
